### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by bjadamson** [carols10cents/rust-conversion-reference#15]
I feel bad opening an "issue" to "thank" you but this crate [really made my day today](https://github.com/bjadamson/softland/blob/master/src/ui.rs#L326)! I just wanted to let you know that.

:)

Searching [google](https://www.google.com/search?q=rust+float+to+string&oq=rust+float+to+string&aqs=chrome.0.69i59j69i60.3367j0j7&sourceid=chrome&ie=UTF-8) for help with my particular problem was unhelpful, until I stumbled upon this crate!

Feel free to close.

**Comment by carols10cents** [comment]
You're very welcome!!! I'm excited to get this issue-- it's so rare to get a *positive* issue on github! <3 Thank you for taking the time out of your day to let me know-- this is the kind of thing that keeps me motivated to keep working on open source :) <3 <3 <3

I'm going to close this, but I'm going to treasure it forever :) 💎
